### ISSUE TITLE
Compilation Impossible: UnityEditor namespace not found

### ISSUE THREAD

**Issue by lobby417** [TheSniperFan/unityserializer-ng#11]
Okay, so I've been using your tool to develop a game of mine. Everything works, except when you try to compile it. The following errors are thrown:
Assets/Plugins/OpenUnityTools/unityserializer-ng/Serialization/StoreMaterials.cs(8,7): error CS0246: The type or namespace name `UnityEditor' could not be found. Are you missing a using directive or an assembly reference?
Assets/Plugins/OpenUnityTools/unityserializer-ng/Serialization/StoreMaterials.cs(146,37): error CS0246: The type or namespace name `Editor' could not be found. Are you missing a using directive or an assembly reference?

I have attempted to fix them, with no avail. Could you please have a look?

**Comment by TheSniperFan** [comment]
I just tried to reproduce the issue with the latest Unity 5 version and the asset's code straight from the master branch. It works on my side.


* Make sure your Unity 5 installation works (If necessary, uninstall, then reinstall it)
* Use the latest code from master

**Comment by lobby417** [comment]
I am on master branch, attempting a reinstall.

**Comment by lobby417** [comment]
Reinstalled, did not work. Can you please demonstrate how you attempted to reproduce the issue? I'll attempt another pull in the meantime.

**Comment by lobby417** [comment]
I should actually specify a little more. In-editor, all the code functions perfectly. Exporting to a player is when I receive the issues. Something to do with Editor-only code being used.

**Comment by TheSniperFan** [comment]
Okay, I see the problem now.
I'll see if a quick-fix is possible and report back in a few minutes.

**Comment by lobby417** [comment]
Thanks for at least looking at the bug.

**Comment by lobby417** [comment]
Sorry to bother you, but is it possible to let me know how far you have managed to fix the bug? Only reason I ask is because my build is ready and I just need this update to export.

**Comment by TheSniperFan** [comment]
Do you use this particular feature?
I'm asking because I 'hacked around the problem' to make it at least build again. The downside is that storing materials is broken outside the editor.

If you don't need it, I would push this workaround into a separate branch so you can build. If you do, you'll need to be patient.

The problem is that Unity doesn't provide an API to get material properties at runtime, only in the editor. This is unfortunate, to say the least. I haven't come up with a good solution yet. Everything I did come up with, is either far too prone to errors or breaks the workflow; Neither of which is acceptable.

**Comment by lobby417** [comment]
Not really. I can try it without materials for now, until the bug is fully resolved.

**Comment by TheSniperFan** [comment]
Check out the materialWiP branch.
It should compile and still work in the editor.

**Comment by lobby417** [comment]
It works! I thought that the serialization would remove all my textures, but everything works, even pulling the level from a server.

**Comment by lobby417** [comment]
I'm not using any of Unity 5's new material tools though, so those probably don't work.

**Comment by TheSniperFan** [comment]
What doesn't work is restoring materials.
The purpose of the StoreMaterial script is to store which material(s) a renderer uses and their properties.
So if some property of a material changes, those changes will be undone when you load a save.

I'm leaving this bugreport open, since the underlying issue isn't resolved yet.

**Comment by lobby417** [comment]
Yup, just noticed the issue. At least I'm able to compile.

**Comment by TheSniperFan** [comment]
Hey, I just wanted to let you know that I figured out a solution and am working on it.
I cannot give you an ETA, because I don't know how long it will take and due to the fact that I'm a little short on time due to a a math exam I'm writing next Monday.

I also wanted to make sure that you know that I cannot guarantee that savefiles of previous versions will be compatible. As of now, it looks like this won't be the case, so be prepared.

**Comment by lobby417** [comment]
Thanks for letting me know.
I don't really mind losing saves, my game is in early stages right now and is only available to a few people.

**Comment by lobby417** [comment]
Hey. I know you're busy, but may I ask how the fix is going?

**Comment by TheSniperFan** [comment]
As I said 5 days ago, I wrote a math exam today.
Good news: I already wrote it this morning.
Good news: It was my last exam for this semester.
Good news: I'm sober (enough) again. :wink:
Good news: I already worked something out.
Bad news: Cannot tell you how long it'll take.

The current plan is to create a hybrid solution that mixes my code and the original one. My code is fast and works with all shaders (even third party ones), but doesn't build because some core functionality is editor-only.
The old solution is slow and inflexible, but the only way to go at runtime.

I wrote a script that opens every scene that is added to the build settings, retrieves every instance of the StoreMaterials script and extracts the shader properties.

I could do two things with this information:
1. I store this in some form of text-file that is included in the build
2. I hard-code everything

Since the shaders are compiled into the game (and thus don't change during runtime), I use option 2 for performance reasons. Unfortunately Unity doesn't support T4 (thanks for that UT :-1:), so I have to write my own code-generator.


What does this mean for you?
It adds one extra-step to your build routine. You need to go to the UnitySerializer window, open the newly added "Materials" tab and click "Get shader data" before you build.
There's also one problem:
You won't be able to use the StoreMaterials script on GameObjects that are root-objects and inactive at the same time. You need to make sure that they're either active or parented to some active GameObject when you generate the shader data.

If you have more questions, let me know.

**Comment by lobby417** [comment]
Thanks for explaining where you are at this moment. I understand that the solution is very complicated.

<insert motivation here>

**Comment by TheSniperFan** [comment]
It's not to be honest.

Iterating over all active scenes: Few lines of code.
Finding all the StoreMaterial scripts in the scene: Few lines of code.
Storing all the important information about the materials and the shaders: Few lines of code.
Code generation: Not implemented yet, but supposedly code generators aren't hard to implement (haven't done it before). I heard that they are only as complicated as you want them to be, which makes sense.

**Comment by TheSniperFan** [comment]
Update time! :smile:

I'd appreciate, if you could test the newest update (check out the materialWiP branch) and report back.

How to use:
* Update the code
* Make sure no GameObjects you want to store the materials of are root objects and inactive at the same time
* Open the wizard, switch to the materials tab and generate the shader database
* Wait for the code generator to finish
* Unity will automatically compile it
* ???
* Profit

The code will be stored in "Assets\Plugins\OpenUnityTools\unityserializer-ng\Serialization\GENERATED\GEN_ShaderDB.cs".
If you take a look at it, you'll understand why I used code generation. You wouldn't want to write that by hand.

**Comment by lobby417** [comment]
I can't test it. My game uses instantiated objects and thus the generator can't find them.

**Comment by lobby417** [comment]
I was just being an idiot. The code works, all I had to do was place an instantiated object in the scene when I generated the database.

Issue is now fixed. I believe it is now save to merge. Closing.

**Comment by TheSniperFan** [comment]
I'll add an option to scan the assets folder and include all shaders that are part of the project. This will waste memory since not all will be used, but it will allow instantiated objects to work without having to place all of them first.
I think it's a fair trade-off, so I'll add the option.
