### ISSUE TITLE
Problem with environment effects [Unity 5.2]

### ISSUE THREAD

**Issue by PentagramPro** [TheSniperFan/unityserializer-ng#23]
Hello, It's me again :)
I'm testing the game I was developing last few months and I noticed that loading the game results in breaking of global lighting.

Before loading: 
![before_load](https://cloud.githubusercontent.com/assets/1443329/9836503/4baad852-5a25-11e5-83fc-5aa9d62d121a.png)

After loading:
![after_load](https://cloud.githubusercontent.com/assets/1443329/9836502/4ba8bff4-5a25-11e5-8731-6db13e7bac94.png)

As you can see, skybox reflection becomes inactive and something changes about ambient lighting. However, I dont see any changes in settings when I pause the scene. Is this bug or some sort of configuration is needed?

**Comment by PentagramPro** [comment]
Experiments with lighting  settings revealed the following. If you change Reflection source to "Custom", you gain same effect as if you saved and loaded the game.

**Comment by PentagramPro** [comment]
Ops, looks like false alarm. Google says that it is a bug in Unity Editor. When I built final package this issue disappeared.

**Comment by TheSniperFan** [comment]
Yeah, I've noticed and reported this bug what feels ages ago.
It's doesn't affect builds, but it's still a **MASSIVE** pain in the ass.

Since Unity 5.3 (due in December) gives us multi-scene editing, we might see a fix then. I don't see how you can work on multiple scenes when only one is lit correctly.
