### ISSUE TITLE
5.3

### ISSUE THREAD

**Issue by Gerlone** [TheSniperFan/unityserializer-ng#27]
Hey,

I just saw a lot of warnings in 5.3 and I was wondering if you are planning to update it at some point?

best regards,

Gerlone

**Comment by TheSniperFan** [comment]
I'll look through them after updating my game.
I remember some of the older warnings like that the old undo-redo system was still used. Then there were newer "You're using the old networking system" warnings.
As far as fixing them goes, I'll have to decide on a case-by-case basis. If it still works, I probably won't. If it's broken and something I need, I'll fix it. If it's broken but not something I need, whether it'll be fixed or scrapped entirely will depend on how difficult fixing it would be.

Network support would be one candidate for being scrapped, because I don't need online savegames. I do realize what a big feature it is though, so I'll keep it in the codebase as long as possible and will gladly accept other people's fixes. I'm neither familiar with the old API, nor with the new one. Fixing it would be a pain.

**Comment by Gerlone** [comment]
I can understand that, espicially the networking part and I don't need networking for now neither. I only used the old system a bit and haven't looked into the new one too much, yet. But I just overlooked it and I saw a lot of warnings related to the new editor api, they implemented nested scenes, so I guess this might create some problems.

Till Iam going to update to 5.3 will take a few weeks anyway, just way too many things that need to be updated first.. was just wondering if you are about to use 5.3 and update this project or if I have to look into that at some point too.

But thanks for the fast response.

**Comment by TheSniperFan** [comment]
I already updated to 5.3 and now my player is broken. I'll fix that, then
I'll look into the serializer.
Good that you brought up multi scene editing...

**Comment by Gerlone** [comment]
Ok, hope it's not too much work and btw. thanks for sharing this project anyways.

**Comment by TheSniperFan** [comment]
I just fixed my player. It was just due to a small change in how LayerMask.GetMask works that I had some problems.
I'll start looking into the problems tomorrow since I'm too tired to tackle something of this scale now.
Multi-scene editing has to be supported. I don't need it because when you actually go ahead and load levels dynamically in the editor, the lighting is still broken. It's still something I don't feel I can ignore (no matter how much I want to :sweat_smile:)

**Comment by Gerlone** [comment]
Oh I see, not really a problem for me atleast for now Iam not planning to use multi scenes, I always need everything more or less loaded. Maybe at some point but for now Iam not working on an open world game nor something that recycles levels. I wasn't really thinking about when else I would really need it, I kinda feel it wouldn't be too bad to organize things but as I said it is not really too bad for me. Since in the end I would need to load everything anyways.
But interesting that lighting creates trouble, but maybe there is a workaround for that.

**Comment by TheSniperFan** [comment]
Which version are you currently using?
Would you mind testing something for me?

When I store the information on a rigidbody, I get the following warning while saving:
```
GetUseConeFriction always returns false. Cone friction is no longer supported, see getFrictionModel instead
```
And this one twice while loading:
```
SetUseConeFriction has no effect. Cone friction is no longer supported, see setFrictionModel instead
```

If you still have a pre-5.3 version, could you see if you get those warnings too?

**Comment by Gerlone** [comment]
Iam on 5.2.1f1 and get this warning too, haven't noticed that before since I never needed to save the rigidbody actually. So far I was only fiddling around with this project haven't checked everything Iam still varying if I write my own system or I use this as a basis.
